# ENPH 213 - Week 4 Lab
In this lab, we will be working on solving systems of linear equations using the Gaussian Elimination method while continuing to develop your Python skills.

When you are finished, please rename this notebook to LastName_ENPH213_Lab4, where LastName is your last name.  Submit that file to onQ.

For marking Parts 1-4 will be marked together (Weighted out of 10) and Parts 5 and 6 will be marked together (Weighted out of 5).

## Part 1

Write a function $GaussPivot(Ab, col)$ that inputs an augmented matrix $Ab$ of an $N \times N$ matrix/2D array $A$ and vector/2D array $b$ of the size $N \times 1$.  The $col$ input to the function is the column that of the pivot element to be assessed.  For this Part, the goal is to simulate finding those rows that would need to be pivoted in a Gaussian Elimination procedure, and no "zeroing" of columns is needed.  Remember that for a generic column $col$ input, a pivot point of $A_{jj}$ means that the pivot row is the same index as the column being reduced and only rows below $A_{jj}$ need to be considered.

Start with the following arrays. 

$A = \begin{bmatrix}
    10 & 9 & 8 & 7 \\
    1  & 2 & 3 & 4 \\
    6  & 6 & 3 & 2 \\
    1  & 5 & 4 & 7
\end{bmatrix}
,\ \ \ b = \begin{bmatrix}
    6  \\
    5  \\
    1  \\
    9  
\end{bmatrix}$

When using the augmented matrix $Ab$, the pivoted matrices I calculated are (for $col = 0, 1, 2$)

$Ab = \begin{bmatrix}
    10 & 9 & 8 & 7 & 6\\
    1  & 2 & 3 & 4 & 5\\
    6  & 6 & 3 & 2 & 1\\
    1  & 5 & 4 & 7 & 9
\end{bmatrix}
,Ab = \begin{bmatrix}
    10 & 9 & 8 & 7 & 6\\
    6  & 6 & 3 & 2 & 1\\
    1  & 2 & 3 & 4 & 5\\
    1  & 5 & 4 & 7 & 9
\end{bmatrix}
,Ab = \begin{bmatrix}
    10 & 9 & 8 & 7 & 6\\
    1  & 2 & 3 & 4 & 5\\
    1  & 5 & 4 & 7 & 9\\
    6  & 6 & 3 & 2 & 1
\end{bmatrix}$

In [7]:
#For the issue that can be resolved using .copy(), I took an alternate method, which was to initialize the arrays from a function each time

import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

#Function to perform a gaussian pivot (take the highest value in column j under Ajj and swap)
def GaussPivot(Ab,col):
    checkArray = np.array(Ab[col: , col])
    
    indexMax = np.argmax(np.abs(checkArray))+col
    
    #Now, swap row #indexMax with the A_(j,col) row
    row = Ab[col,:].copy()
    Ab[col, :] = Ab[indexMax, :]    
    Ab[indexMax, :] = row
    return Ab

#Initializes the array in between print statements (To prevent the stack using the wrong Ab)
def InitArray():
    #Two arrays being used
    A = np.array([10,9,8,7,1,2,3,4,6,6,3,2,1,5,4,7])
    A = np.reshape(A,(4,4))
    b = np.array([[6],[5],[1],[9]])

    #Adding the b array onto the A to form Ab to be send to the function
    Ab = np.append(A,b,axis=1)
    return Ab

#Here, I am initializing the array in between each print to prevent any pivoting of already-used arrays
Ab = InitArray()
print(GaussPivot(Ab,0))
Ab = InitArray()
print(GaussPivot(Ab,1))
Ab = InitArray()
print(GaussPivot(Ab,2))

[[10  9  8  7  6]
 [ 1  2  3  4  5]
 [ 6  6  3  2  1]
 [ 1  5  4  7  9]]
[[10  9  8  7  6]
 [ 6  6  3  2  1]
 [ 1  2  3  4  5]
 [ 1  5  4  7  9]]
[[10  9  8  7  6]
 [ 1  2  3  4  5]
 [ 1  5  4  7  9]
 [ 6  6  3  2  1]]


## Part 2

Write a function GaussElim(Ab, col) that inputs an augmented matrix $Ab$ of an $N \times N$ matrix/2D array $A$ and vector/2D array $b$ of the size $N \times 1$.  The $col$ input to the function is the column that of the pivot element, which will have zeros underneath.  For this Part, the goal is to only have zeros under the first pivot element ($A_{00}$), so col = 0.  It does _not_ have to put the matrix in triangular form.  Pivoting should be included in the function using the $GaussPivot(Ab, col)$ function above.

When I entered the $Ab$ array from Part 1, I got the result:

$Ab = \begin{bmatrix}
    10 & 9 & 8 & 7 & 6\\
    0  & 1.1 & 2.2 & 3.3 & 4.4 \\
    0  & 0.6 & -1.8 & -2.2 & -2.6\\
    0  & 4.1 & 3.2 & 6.3 & 8.4
\end{bmatrix}$

In [55]:
def GaussElim(Ab,col):
    #Getting the depth and width of the array
    N,M = Ab.shape
    
    #Making sure that we perform a Gauss Pivot before dividing
    Ab = GaussPivot(Ab,col)
    
    #Loop to divide each consecutive row by the formula using the first in the sequence
    for i in range(col+1,N):
        Ab[i] = Ab[i]-((Ab[i][col]/Ab[col][col])*Ab[col])
    return Ab

#A function that initializes the arrays to be used (this time as floats instead of integers)
def InitArrayDec():
    #Two arrays being used (Just added decimals here to show the actual result and avoid chopping off the ends)
    A = np.array([10.0,9.0,8.0,7.0,1.0,2.0,3.0,4.0,6.0,6.0,3.0,2.0,1.0,5.0,4.0,7.0])
    A = np.reshape(A,(4,4))
    b = np.array([[6.0],[5.0],[1.0],[9.0]])

    #Adding the b array onto the A to form Ab to be send to the function
    Ab = np.append(A,b,axis=1)
    return Ab

Ab = InitArrayDec()    
print(GaussElim(Ab,0))

[[10.   9.   8.   7.   6. ]
 [ 0.   1.1  2.2  3.3  4.4]
 [ 0.   0.6 -1.8 -2.2 -2.6]
 [ 0.   4.1  3.2  6.3  8.4]]


## Part 3

Write a third function UpTriang(A, b) that inputs an $N \times N$ matrix/2D array $A$ and vector/2D array $b$ of the size $N \times 1$.  This function should output an augmented matrix in upper triangular form.  In UpTriang(A, b), call the GaussElim(Ab, col) function you created above and index over the appropriate $col$ values.  The $col$ values should not be set, but instead should be derived from the size of $A$.  Using the $A$ and $b$ arrays above, my code generated the following outputs at the next two steps in the elimination process (decimals trucated).

$Ab = \begin{bmatrix}
10 &   9 &  8&  7&    6 \\
0  &  4.1& 3.2  &6.3  &  8.4  \\
0  &   0 &  -2.268 & -3.12195 & -3.829268 \\
0  &   0 &  1.341 &  1.6097 &  2.1463 
\end{bmatrix}$

$Ab = \begin{bmatrix}
10 &   9 &  8&  7&    6 \\
0  &  4.1& 3.2  &6.3  &  8.4  \\
0  &   0 &  -2.268 & -3.12195 & -3.829268 \\
0  &   0 &  0 &  -0.236559 &  -0.11828  
\end{bmatrix}$

If everything is working except for your pivoting, then you should see

$Ab = \begin{bmatrix}
10 &   9 &  8&  7&    6 \\
0  &  1.1& 2.2  &3.3  &  4.4  \\
0  &   0 &  -3 & -4 & -5 \\
0  &   0 &  0 & 0.6667 &  0.3333 
\end{bmatrix}$

In [79]:
#Function to perform Gaussian Elimination on an N*M matrix
def UpTriang(A,b):
    #Find the depth and width of A
    N,M = A.shape
    
    #Create Ab
    Ab = np.append(A,b,axis=1)  
    
    #Loop through and perform the func GaussElim on each consecutive column
    for i in range(0,N-1):
        Ab = GaussElim(Ab,i)
    return Ab

#Two arrays being used (Just added decimals here to show the actual result and avoid chopping off the ends)
A2 = np.array([10.0,9.0,8.0,7.0,1.0,2.0,3.0,4.0,6.0,6.0,3.0,2.0,1.0,5.0,4.0,7.0])
A2 = np.reshape(A2,(4,4))
b2 = np.array([[6.0],[5.0],[1.0],[9.0]])       

#print
print(UpTriang(A2,b2))

[[10.          9.          8.          7.          6.        ]
 [ 0.          4.1         3.2         6.3         8.4       ]
 [ 0.          0.         -2.26829268 -3.12195122 -3.82926829]
 [ 0.          0.          0.         -0.23655914 -0.11827957]]


## Part 4

Finally, write a function $BackSub(A, b)$ that inputs an $N \times N$ matrix/2D array $A$ and vector/2D array $b$ of the size $N \times 1$.  This function should call the $UpTriang(A, b)$ function and then use Back Substitution from the lecture to solve the system of equations $\mathbf{Ax=b}$.  This function should output a 1-D array of values that correspond to the $x_i$ in the $\mathbf x$ array.  To check your answer, substitute $\mathbf x$ into $\mathbf{Ax=b}$ to recover the values in $\mathbf b$.

In [34]:
#Function to perform back substitution on an augmented matrix
def BackSub(A,b):
    N,M = A.shape
    
    #Upper triangular
    Ab = UpTriang(A,b)
    for i in range(0,N):
        Ab[i] = Ab[i]/Ab[i][i]
    
    #Nested for loop in order to perform the algorithm calculation (j goes up the matrix, k goes "down" from j each time)     
    for j in range(N-2,-1,-1):
        for k in range(j+1,N):
            Ab[j] = Ab[j]-Ab[j][k]*Ab[k]
     
    return Ab[:,-1]

print(BackSub(A2,b2)) 

[-1.   0.5  1.   0.5]


## Part 5

You now have all the tools to write a function to return the inverse of a matrix.  Write a function $myInv(A)$ that inputs an $N \times N$ matrix/2D array $A$ and returns its inverse.  You can work with the array $A$ above, and to verify that your new matrix is indeed the inverse, evaluate $\mathbf{ A A^{-1} = I}$.

Q: If your $\mathbf{ A A^{-1} = I}$ is not exactly the identity matrix, please explain why?

In [37]:
#Same function as above, but returns the whole arrray instead of the last column
def BackSubFull(A,b):
    N,M = A.shape
    
    #Upper triangular
    Ab = UpTriang(A,b)
    for i in range(0,N):
        Ab[i] = Ab[i]/Ab[i][i]
    
    #Nested for loop in order to perform the algorithm calculation (j goes up the matrix, k goes "down" from j each time)   
    for j in range(N-2,-1,-1):
        for k in range(j+1,N):
            Ab[j] = Ab[j]-Ab[j][k]*Ab[k]     
    return Ab

#Function to find the inverse of a matrix
def myInv(A):
    #Dimensions
    N,M = A.shape
    #Identity Matrix
    I = np.identity(N)
    #Augmented matrix [A|I]
    Aaug = np.append(A,I,axis=1)
    
    #Back Sub in order to "swap" to the inversion
    returnMatrix = BackSubFull(A,I)
    return returnMatrix[:,N:]

#Printing out the inverse
print(np.round(myInv(A2),3))

print("\n")

#Checking to see if AA' = I
print(np.round(np.dot(A2,myInv(A2))))

####Q: The numbers experience some rounding during the calculation, and as they are not integers, this can lead to numbers that are not EXACTLY 0, yet very close (ex. -0 in the array)
####Q: np.round is then used in order to make the final result more presentable (instead of a number to the power of snegative 30...)

[[ 1.545 -3.455 -2.     1.   ]
 [-1.045  1.955  1.5   -0.5  ]
 [-2.182  5.818  3.    -2.   ]
 [ 1.773 -4.227 -2.5    1.5  ]]


[[ 1.  0. -0.  0.]
 [ 0.  1. -0.  0.]
 [ 0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]


## Part 6

Write a another function UpTriang2(A, b) that inputs an $N \times N$ matrix/2D array $A$ and vector/2D array $b$ of the size $N \times 1$.  This function should output an augmented matrix in upper triangular form.  In UpTriang2(A, b), call the GaussElim(Ab, col) function you created above as you did before, but instead of indexing over the appropriate $col$ values, remove the Row 0 and Column 0 parts of the array to create a slightly smaller array.  [Note, you should store the Row 0 value to create the upper triangular matrix.]  Then run GaussElim(Ab, col), for col=0, on this new smaller array, save Row 0, create a smaller array, and iterate until Gaussian Elimination is complete.  Test you algorithm against the $A$ and $b$ you used above.

There is a thought that by working on smaller arrays, this method to create upper triangular matrices could be faster.  Test this idea by creating a large array of $1000 \times 1000$ random values and create an upper triangular array use the two functions you have created.  Time their performance using the %timeit command before calling the functions. [Note: $b$ will need to be a 2D array of $1 \times 1000$ elements.  "Up-Size" the array by using np.array([np.random.rand(1000)]).

Q: Briefly discuss which function was faster and hypothesize why.  Also, time your functions for $100 \times 100$ and $10 \times 10$ input arrays.  How does the run-time change for changing N?  Does this make sense?  Consider this relative to the approximate number of calculations your function has to do.

In [75]:
def UpTriang2A(A,b):
    N,M = A.shape
    
    #Create Ab
    Ab = np.append(A,b,axis=1)
    
    #Create empty array
    FinalArray = np.zeros((N,N+1))
    
    #Loop through and export each consecutive row into the new matrix (staggered into the ith column)
    for i in range(0,N):
        #GaussElim
        Ab = GaussElim(Ab,0)
        #Export
        FinalArray[i,i:]=Ab[0]
        #Slice
        Ab = Ab[1:,1:]
        
    return FinalArray

#Print Output
print(UpTriang2A(A2,b2)) 

#TIME TO RACE!!!
#1000
RaceA = np.array(np.random.rand(1000,1000))
Raceb = np.array(np.random.rand(1000,1))

print("\n")

print("Loop 1:")
%timeit UpTriang(RaceA,Raceb)
print("Loop 2:")
%timeit UpTriang2A(RaceA,Raceb)

print("\n")
#100
RaceA = np.array(np.random.rand(100,100))
Raceb = np.array(np.random.rand(100,1))

print("Loop 1:")
%timeit UpTriang(RaceA,Raceb)
print("Loop 2:")
%timeit UpTriang2A(RaceA,Raceb)

print("\n")
#10
RaceA = np.array(np.random.rand(10,10))
Raceb = np.array(np.random.rand(10,1))

print("Loop 1:")
%timeit UpTriang(RaceA,Raceb)
print("Loop 2:")
%timeit UpTriang2A(RaceA,Raceb)

#Here, the second function was faster, as it will perform calculations on a progressively smaller matrix with each loop run. This means that as the function progresses, it will outperform the original
#However, if the number of values is reduced, then it will be required to perform an EXTRA calculation (cutting out the needed row), meaning it will perform worse (as shown in the N=100 and N=10).
#At low N, this extra operation will NOT BE WORTH IT, and take up more time to perform. At high N, this function will become more efficient.

[[10.          9.          8.          7.          6.        ]
 [ 0.          4.1         3.2         6.3         8.4       ]
 [ 0.          0.         -2.26829268 -3.12195122 -3.82926829]
 [ 0.          0.          0.         -0.23655914 -0.11827957]]


Loop 1:
2.6 s ± 69.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Loop 2:
2.24 s ± 14.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Loop 1:
16.7 ms ± 62.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Loop 2:
16.9 ms ± 73.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Loop 1:
211 µs ± 1.24 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
Loop 2:
231 µs ± 1.46 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Acknowledgements

Please comment on any help that you received from your group members or others concerning this Lab assignment.